baseURL: '/'
languageCode: 'en-us'
title: 'Isagani Jaen'
theme: 'PaperMod'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

menu:
  main:
    - identifier: resume
      name: ✨Resume
      url: /resume/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20  
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40              


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Isagani Jaen
  description: "Isagani Jaen's online portfolio"
  keywords: [Blog, Portfolio, Resume]
  author: Isagani Jaen
  # author: ["Me", "You"] # multiple authors
  # images: ["https://pbs.twimg.com/profile_images/1752594393046081536/HyzWEsBK_400x400.jpg"]
  # images: ["img/isagani-jaen-fb.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  # assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  # label:
    # text: "Isagani Jaen"
    # icon: /apple-touch-icon.png
    # iconHeight: 35  

  profileMode:
    enabled: true
    # title: "<Title>" # optional default will be site title
    subtitle: "System Development Senior Analyst"
    imageUrl: "img/isagani-jaen-fb.jpg" # optional
    imageTitle: "Isagani Jaen" # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size
    buttons:
      - name: Blog
        url: "/blog"
      - name: Resume
        url: "/resume"

  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/isaganijaen"
    - name: "github"
      url: "https://github.com/isaganijaen"
    - name: "facebook"
      url: "https://facebook.com/isagani.jaen"                
    - name: "instagram"
      url: "https://instagram.com/isagani.jaen"  
    - name: "x"
      url: "https://twitter.com/isaganijaen"  
    - name: "buymeacoffee"
      url: "https://buymeacoffee.com/isaganijaen"  


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"      

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    linkFullImages: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]      



# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai


outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
      renderer:
      hardWraps: false
      unsafe: true
      xhtml: false